name: dapr_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  freezed_annotation:
  json_annotation: ^4.3.0
  http: ^0.13.4  
  grpc: ^3.0.2
  dapr_proto: ^0.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner:
  freezed:
  json_serializable: