name: E2E & unit tests

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  run-all-tests:
    runs-on: ubuntu-latest          
    env:
      DAPR_INSTALL_URL: https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
      SRV_COMP_DIR: ../../infrastructure/gh_actions_components/server
      CLNT_COMP_DIR: ../../infrastructure/gh_actions_components/client
    services:
      dapr_rabbitmq:        
        image: rabbitmq:3-management-alpine        
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v2

      - name: Dapr - Install CLI
        run: wget -q ${{ env.DAPR_INSTALL_URL }} -O - | /bin/bash -s ${{ env.DAPR_CLI_VER }}
        
      - name: Dapr - Initialize
        run: dapr init
        
      # - name: Run RabbitMQ container
      #   run: docker run -d -p 5672:5672 --name dapr_rabbitmq rabbitmq:3-management-alpine
      - name: List docker containers
        run: docker ps

      - name: Install dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable    
      
      - name: Install Melos
        run: dart pub global activate melos
      
      - name: Install coverage package for dart
        run: dart pub global activate coverage
      
      - name: Run client http e2e tests        
        run: |
          melos run test:client:e2e:http
          export test_result=$(tail -1 package/dapr_client/test/reports/tests_client_http.json)
          if fromJSON(${test_result}).success
            echo "No error found: All tests passed";
          else
            exit 1;
          fi

#       - name: Run client grpc e2e tests        
#         run: |
#           melos run test:client:e2e:grpc | tee cln_grpc.txt
#           if grep "Some tests failed." -i cln_grpc.txt -q; then
#             exit 1;
#           else
#             echo "No error found: All tests passed";
#           fi

#       - name: Run server http e2e tests        
#         run: |
#           melos run test:server:e2e:http | tee srv_http.txt
#           if grep "Some tests failed." -i srv_http.txt -q; then
#             exit 1;
#           else
#             echo "No error found: All tests passed";
#           fi

#       - name: Run server grpc e2e tests        
#         run: |
#           melos run test:server:e2e:grpc | tee srv_grpc.txt
#           if grep "Some tests failed." -i cln_grpc.txt -q; then
#             exit 1;
#           else
#             echo "No error found: All tests passed";
#           fi
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
