name: Run Dapr Dart-sdk E2E & unit tests.

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    env:
      DAPR_INSTALL_URL: https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
    services:
      # Use the following services instead of dapr's for testing.
      # This is to keep the naming of the containers consistent across tests.
      # Maybe in future we can avoid and use Dapr's services directly.
      redis:
        container_name: "test-redis"
        image: "redis:alpine"
        ports:
          - "6380:6379"
      rabbitmq:
        container_name: 'test-rabbitmq'
        image: rabbitmq:3-management-alpine
        ports:
          - 5672:5672
          - 15672:15672
      placement:
        container_name: "test-dapr-placement"
        image: "daprio/dapr"
        command: ["./placement", "-port", "50006"]
        ports:
          - "50006:50006"
    steps:
      - uses: actions/checkout@v2

      - name: Dapr - Install CLI
        run: wget -q ${{ env.DAPR_INSTALL_URL }} -O - | /bin/bash -s ${{ env.DAPR_CLI_VER }}
      
      - name: Dapr - Initialize slim
        run: dapr init --slim
      
      - name: Install Melos
        run: dart pub global activate melos
      
      - name: Install coverage package for dart
        run: dart pub global activate coverage
    
      - name: Run all end-to-end tests
        run: melos run test:e2e
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

