name: Run Dapr Dart-sdk E2E & unit tests.

on:
  push:
    branches:
      - master
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - release-*

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    container: dart:stable        
    env:
      DAPR_INSTALL_URL: https://raw.githubusercontent.com/dapr/cli/master/install/install.sh
    services:
      dapr_rabbitmq:        
        image: rabbitmq:3-management-alpine        
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v2
      - name: install wget and curl
        run: apt-get -y install --no-install-recommends wget curl

      - name: Dapr - Install CLI
        run: wget -q ${{ env.DAPR_INSTALL_URL }} -O - | /bin/bash -s ${{ env.DAPR_CLI_VER }}
      
      - name: Dapr - Initialize
        run: dapr init
        
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable    
      
      - name: Install Melos
        run: dart pub global activate melos
      
      - name: Install coverage package for dart
        run: dart pub global activate coverage
    
      - name: Run all end-to-end tests
        run: melos run test:e2e
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

